[package]
name = "permissions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing.workspace = true
uuid = {workspace = true, features = ["serde", "v4"]}
async-trait = "0.1.85"
chrono = { version = "0.4.39", features = ["serde"]}

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
tokio-test = {workspace = true}
[lints]
workspace = true
